### ISSUE TITLE
Gnome disks in dark mode has some light text on a light background

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-disk-utility#3]
**Describe the problem:**
In dark theme, the text on the partition chooser is light, and remains light when a partition is selected, resulting in the text being difficult to read.
![disks-dark-contrast](https://user-images.githubusercontent.com/13512097/66865170-e41de800-ef53-11e9-8415-e40b0aa46506.png)

**Steps to reproduce:**
Apply dark theme and open Disks.

**Distribution:**
Pop!_OS 19.10

**Pop version:**
```
system76@pop-os:~$ apt policy pop-gtk-theme 
pop-gtk-theme:
  Installed: 5.0.0~1571164861~19.10~f0f895d
  Candidate: 5.0.0~1571164861~19.10~f0f895d
  Version table:
 *** 5.0.0~1571164861~19.10~f0f895d 1002
       1002 http://apt.pop-os.org/staging/master eoan/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master eoan/main i386 Packages
        100 /var/lib/dpkg/status
     5.0.0~1570998216~19.10~cbbf790 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
```

**Comment by keftie22** [comment]
This issue has either come back for some reason or continues to be a thing as of the 22.04 beta on a fresh install.

![disks_pop_theme_contrast](https://user-images.githubusercontent.com/101351551/161384141-5129374a-7eff-469b-9cb5-138272b41f48.png)

**Comment by jackpot51** [comment]
Yep, see #5
